

name: action_test


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout private action
        uses: actions/checkout@v2
        with:
          repository: aptyInc/apty-branch-manager-action
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }} # stored in GitHub secrets
          path: .github/actions/apty-branch-manager-action
      - name: Run My Action
        uses: ./.github/actions/apty-branch-manager-action
        env:
          NAME: 'Sai Umesh'