

name: action_test


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      
      - uses: aptyInc/apty-branch-manager-action@main
        name: checking private action