

name: admin


on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Finding size diff
        id: size_diff
        run: chmod +x ./find_diff.sh && ./find_diff.sh
        env:
          BASE_BRANCH: "origin/master"
          CURRENT_BRANCH: "diff"
      
      - name: Printing diff
        run: echo "{steps.size_diff.outputs.size}"
