

name: server


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows:
      - "admin"
    types:
      - completed

jobs:
  build_1:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
