

name: server

on:
  workflow_run:
    workflows: ["admin"]
    types:
      - completed

jobs:
  rules:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    name: Rules
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.validations.outputs.branch_name }}
      should_deploy: ${{ steps.validations.outputs.should_deploy}}
      non_prod_deploy: ${{ steps.validations.outputs.non_prod_deploy}}
      prod_deploy: ${{ steps.validations.outputs.prod_deploy}}
    steps:
      - name: Fetch Branch Name
        uses: aptyInc/gha-branch-name@0.7.0
        id: validations
  build_1:
    needs: ["rules"]
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Getting user profile url
        id: user_profile
        uses: saiumesh535/gh-avatar-url@main
        with:
          username: ${{github.actor}}
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI_FAILURE }}
          overwrite: "{
              title: `Accounts ${{ needs.rules.outputs.branch_name }} Deployment failed 😭`,
              summary: `Deployment Failed 😭 Author: ${{github.actor}}`,
              sections: [
                {
                  activityTitle: `Accounts ->> ${{ needs.rules.outputs.branch_name }}`,
                  activitySubtitle: `Made changed by ${{github.actor}}`,
                  'activityImage': `${{steps.user_profile.outputs.profile_url}}`,
                  'facts': [
                    {name: `Deployed by:`, value: `${{github.actor}}` }
                  ]
                }
              ]
            }"
      
