

name: server

on:
  workflow_run:
    workflows: ["admin"]
    types:
      - completed

jobs:
  build_1:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Run a one-line script
        run: "failed, send notification"
